# file: roles/minikube_install/tasks/main.yml
---
- name: Checking for existing minikube
  ansible.builtin.stat:
    path: /usr/local/bin/minikube
  register: minikube_check

- block:
    - name: Downloading minikube-linux-amd64
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /tmp/minikube-linux-amd64
        owner: '{{ target_user }}'
        group: '{{ target_group }}'
        mode: 0644

    - name: Installing Minikube
      ansible.builtin.shell: |
        set -o pipefail
        install /tmp/minikube-linux-amd64 /usr/local/bin/minikube
      args:
        executable: /bin/bash
        warn: false
        creates: /usr/local/bin/minikube
  when: not minikube_check.stat.exists

- name: Cleaning up /tmp/minikube-linux-amd64
  ansible.builtin.file:
    path: /tmp/minikube-linux-amd64
    state: absent

# Regarging the use of sudo below instead of the 'become' directive:
# Even though the target_user (e.g. vagrant) is added to the docker
# group as the playbook runs, that group membership will not be picked
# up until a new session is started. Thus, sudo is used as a workaround.
- name: Starting minikube cluster (this will take some time)
  ansible.builtin.shell: |
    set -o pipefail
    sudo -u vagrant minikube start
    sudo -u vagrant minikube addons enable ingress
    sudo -u vagrant minikube addons list
  args:
    executable: /bin/bash
    warn: false
  become: true
  become_user: '{{ target_user }}'
    creates: /var/lib/docker/volumes/minikube
  become: false
  register: minikube_startup

- name: Displaing minikube startup
  ansible.builtin.debug:
    var: minikube_startup.stdout
...
