# file: roles/helm_install/tasks/main.yml
---
- name: Installing Helm GPG key
  ansible.builtin.shell: |
    set -o pipefail
    curl https://baltocdn.com/helm/signing.asc | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  args:
    executable: /bin/bash
    warn: false
    creates: /usr/share/keyrings/helm.gpg

- name: Installing dependencies
  ansible.builtin.package:
    name: apt-transport-https
    state: present

- name: Creating Helm apt source
  ansible.builtin.shell: |
    set -o pipefail
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | \
    sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  args:
    executable: /bin/bash
    warn: false
    creates: /etc/apt/sources.list.d/helm-stable-debian.list

- name: Installing helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true
...
