apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pizza-express
  name: pizza-express
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pizza-express
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pizza-express
    spec:
      containers:
        - env:
            - name: REDIS
              value: pizza-redis
            - name: TZ
              value: America/New_York
          image: v01ddweller/pizza:latest
          livenessProbe:
            exec:
              command:
                - curl
                - http://localhost:3000
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: test-pizza
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
